// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortGeneration() {
  return window['go']['main']['App']['AbortGeneration']();
}

export function CycleModel() {
  return window['go']['main']['App']['CycleModel']();
}

export function ExportSession(arg1) {
  return window['go']['main']['App']['ExportSession'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetSessionID() {
  return window['go']['main']['App']['GetSessionID']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InitAgent(arg1, arg2) {
  return window['go']['main']['App']['InitAgent'](arg1, arg2);
}

export function IsGenerating() {
  return window['go']['main']['App']['IsGenerating']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetThinkingLevel(arg1) {
  return window['go']['main']['App']['SetThinkingLevel'](arg1);
}
