// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortGeneration():Promise<void>;

export function CycleModel():Promise<string>;

export function ExportSession(arg1:string):Promise<string>;

export function GetCurrentTime():Promise<string>;

export function GetModelInfo():Promise<Record<string, string>>;

export function GetSessionID():Promise<string>;

export function GetStats():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function InitAgent(arg1:string,arg2:string):Promise<void>;

export function IsGenerating():Promise<boolean>;

export function NewSession():Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetThinkingLevel(arg1:string):Promise<void>;
